/**
 * A simple random number generator (RNG) using the SFC32 algorithm.
 * This function generates a sequence of 32-bit floating-point numbers in the range [0, 1).
 *
 * @param {number} a - The first state value.
 * @param {number} b - The second state value.
 * @param {number} c - The third state value.
 * @param {number} d - The fourth state value.
 *
 * @returns {Object} - An object containing the updated state values and the generated random number.
 * @returns {number} object.a - The updated first state value.
 * @returns {number} object.b - The updated second state value.
 * @returns {number} object.c - The updated third state value.
 * @returns {number} object.d - The updated fourth state value.
 * @returns {number} object.random - The generated random number in the range [0, 1).
 *
 * @example
 * const { a, b, c, d, random } = sfc32(12345, 67890, 34567, 89012);
 * console.log(`Random number: ${random}`);
 */
function sfc32(a, b, c, d) {
  a |= 0;
  b |= 0;
  c |= 0;
  d |= 0;
  let t = (((a + b) | 0) + d) | 0;
  d = (d + 1) | 0;
  a = b ^ (b >>> 9);
  b = (c + (c << 3)) | 0;
  c = (c << 21) | (c >>> 11);
  c = (c + t) | 0;
  const random = (t >>> 0) / 4294967296;
  return { a, b, c, d, random };
}

/**
 * Generates the next state of the random number generator (RNG) based on the provided current state.
 *
 * @param {Object} rng - The current state of the RNG.
 * @param {number} rng.seed - The initial seed used for the RNG.
 * @param {number} rng.a - The first state value used for the RNG.
 * @param {number} rng.b - The second state value used for the RNG.
 * @param {number} rng.c - The third state value used for the RNG.
 * @param {number} rng.d - The fourth state value used for the RNG.
 * @param {number} rng.random - The random number [0, 1) generated by the RNG.
 *
 * @returns {Object} - The next RNG state.
 * @returns {number} returns.seed - The initial seed used for the RNG.
 * @returns {number} returns.a - The first state value used for the RNG.
 * @returns {number} returns.b - The second state value used for the RNG.
 * @returns {number} returns.c - The third state value used for the RNG.
 * @returns {number} returns.d - The fourth state value used for the RNG.
 * @returns {number} returns.random - The random number [0, 1) generated by the RNG.
 */
function next(rng) {
  const { a, b, c, d, random } = sfc32(rng.a, rng.b, rng.c, rng.d);
  return {
    ...rng,
    a,
    b,
    c,
    d,
    random,
  };
}

/**
 * Creates a state-based number generator with the provided seed.
 * If no seed is provided, a random seed will be generated.
 *
 * @param {string} seed - A hex string of length 32
 *
 * @returns {Object} - An object representing the RNG instance.
 * @returns {Array} object.seed - The initial seed used for the RNG.
 * @returns {number} object.random - The random number [0, 1) generated by the RNG. Initial value is -1.
 *
 * @example
 * const rand = newRNG(seed);
 * rand.seed // returns seed
 *
 * let nextRand = rngLib.next(rand);
 * nextRand.random // returns next random number 'a' in [0, 1)
 * nextRand = rngLib.next(rand);
 * nextRand.random // returns next random number 'b' in [0, 1)
 *
 * rngLib.next(rand).random // returns next random number 'a' in [0, 1)
 * rngLib.next(rand).random // returns same random number 'a' in [0, 1)
 * rngLib.next(rngLib.next(rand)).random // returns next random number 'b' in [0, 1)
 */
function newRNG(seed) {
  if (!validSeed(seed)) {
    seed = newSeed();
  }

  const [a, b, c, d] = unpackSeed(seed);
  return {
    seed,
    a,
    b,
    c,
    d,
    random: -1,
  };
}

/**
 * Checks if the provided seed is a valid hex string of length 32.
 *
 * @param {string} seed - The seed to be validated.
 * @returns {boolean} - Returns true if the seed is a string of length 32, otherwise false.
 */
function validSeed(seed) {
  return typeof seed === 'string' && seed.length === 32;
}

/**
 * Generates a new random seed, represented as a hex string of length 32.
 * The seed is generated by generating four random 32-bit unsigned integers
 * and concatenating their hex representations in the order a, b, c, d.
 *
 * @returns {string} - A new random seed as a hex string of length 32.
 */
function newSeed() {
  return packSeed(
    (Math.random() * 2 ** 32) >>> 0,
    (Math.random() * 2 ** 32) >>> 0,
    (Math.random() * 2 ** 32) >>> 0,
    (Math.random() * 2 ** 32) >>> 0
  );
}

/**
 * Converts four 32-bit unsigned integers into a single hex string of length 32.
 * @param {number} a - The first 32-bit unsigned integer.
 * @param {number} b - The second 32-bit unsigned integer.
 * @param {number} c - The third 32-bit unsigned integer.
 * @param {number} d - The fourth 32-bit unsigned integer.
 * @returns {string} - The hex string representation of the four input numbers, in the order a, b, c, d.
 */
function packSeed(a, b, c, d) {
  return [a, b, c, d].map((num) => num.toString(16).padStart(8, '0')).join('');
}

/**
 * Converts a hex string of length 32 into four 32-bit unsigned integers.
 * The hex string is expected to be in the order a, b, c, d.
 *
 * @param {string} hexString - The hex string to convert.
 *
 * @returns {Array} - The four 32-bit unsigned integers in the order a, b, c, d.
 */
function unpackSeed(hexString) {
  return [
    parseInt(hexString.slice(0, 8), 16),
    parseInt(hexString.slice(8, 16), 16),
    parseInt(hexString.slice(16, 24), 16),
    parseInt(hexString.slice(24, 32), 16),
  ];
}

const rngLib = { next };
export { newRNG as default, rngLib };
